# Site settings
title: Basha Tahamal
nickname: Basha
fullname: M. Hawatif Basharuddin R. T.
email: m.hawatif.basharuddin@mail.ugm.ac.id
url: https://github.com/bashatahamal
description: "Muhammad Hawatif Basharuddin Rabbani Tahammal portfolio web"
keywords: "Basha, Computer Vison, Machine Learning, Software Engineer"
skills: "Software Engineer - Machine Learning - Computer Vision"
meta_author: Tahamal Basha
about: Hi, my name is Basha, I have a degree in the Department of Computer Science and Electronics, Gadjah Mada University, majoring in Electronics and Instrumentation with cum laude predicate. I can learn things quickly and creatively. I am also a person who does not give up easily and an excelent thinker. When working in a team I play most of the role as a leader and as a member I can still contribute with my creative ideas and collaborate effectively. I can adapt to various conditions quickly by always trying to push myself to learn to be better and trying to take initiative. I have an interest in software in general and what I have been researching and working on recently is machine learning, computer vision and a little bit about web development. This is just the beginning of what I can do and I believe in my potential to be able to do more and benefit society with the skills I have. 

baseurl: ""
theme-home: theme-home-builtin-1.html
theme-projects: theme-projects-builtin-1a.html
theme-essays: theme-essays-builtin-1a.html
theme-bio: theme-bio-builtin-1.html

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
#color:
  #primary: 18bc9c #80B3FF
  #primary-rgb: "24,288,156" #"128,179,255"
  #secondary: 2c3e50 #FD6E8A
  #secondary-dark: 233140 #A2122F
color:
  primary: 757575
  primary-rgb: "117,117,117"
  secondary: 212121
  secondary-dark: "000000"

# Footer settings
footer:
  copyright: Basha Tahamal
  location: Address
  social: Around the Web
  credits: Phone Number

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/bashatahamal
  - title: paper-plane
    url: http://t.me/bashatahamal
  - title: envelope
    url: mailto:m.hawatif.basharuddin@mail.ugm.ac.id
  - title: linkedin
    url: http://linked.in/bashatahamal
  - title: github
    url: http://github.com/bashatahamal

# Postal address (add as many lines as necessary)
address:
  - line: Jl. Magelang km 8
  - line: Sleman, Yogyakarta 55285

# Credits content
credits: '+6285643755459'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
